name: Build & Install packages

on:
  workflow_call:

jobs:
  build-packages:
    name: Install & build packages
    if: ${{ github.event.inputs.environment == 'localhost' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        if: ${{ github.event.inputs.environment == 'localhost' || github.event_name == 'pull_request' }}
        uses: actions/setup-node@v3
        with:
          node-version: ">=20.0.0"

      - name: Install all packages
        if: ${{ github.event.inputs.environment == 'localhost' || github.event_name == 'pull_request' }}
        run: yarn

      - name: Build application
        if: ${{ github.event.inputs.environment == 'localhost' || github.event_name == 'pull_request' }}
        run: yarn build-localhost

      - name: Save build folder
        if: ${{ github.event.inputs.environment == 'localhost' || github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: build
